[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iterativerecursion"
version = "0.6"
description = "A Python module to simulate recursive function calls using iteration, providing explicit control over execution flow and avoiding stack overflow issues."
readme = "README.md"

license = "MIT"
license-files = ["LICENSE"]

authors = [
    {name = "Carlos A. PlanchÃ³n", email = "carlosandresplanchonprestes@gmail.com"}
]
keywords = ["iterative", "recursion"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
requires-python = ">=3.10"

[project.urls]
Repository = "https://github.com/carlosplanchon/iterativerecursion"

[project.optional-dependencies]
dev = ["pytest>=7.0.0"]

[tool.setuptools]
packages = ["iterativerecursion"]
